 apiVersion: networking.istio.io/v1alpha3
 kind: VirtualService
 metadata:
   name: graprometheusfana-virtual-service
   namespace: istio-system

 spec:
   hosts:
   - "prometheus.sujangcloud.uk"
   gateways:
   - istio-system/istio-ingress-gateway
   http:

 #Kiali traffic routing
   - match:
     - uri:
         prefix: /
     route:
     - destination:
         host: prometheus.istio-system.svc.cluster.local
         port:
           number: 9090

