apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: futakai-virtual-service
spec:
  hosts:
  - "futakai.com"
  gateways:
  - istio-ingress-gateway
  http:
  - match:
    - uri:
        prefix: /contents
    # - uri:
    #     prefix: /delay
    route:
    - destination:
        port:
          number: 80
        host: futakai-contents-service.futakai-contents.svc.cluster.local