apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: futakai-virtual-service
  namespace: futakai-contents

spec:
  hosts:
  - "futakai.com"
  gateways:
  - istio-system/istio-ingress-gateway
  http:
  - match:
    - uri:
        prefix: /allVideos
    route:
    - destination:
        host: futakai-contents-service.futakai-contents.svc.cluster.local
        port:
          number: 80


  - match:
    - uri:
        prefix: "/backend"
    route:
    - destination:
        host: futakai-be-service.futakai-be.svc.cluster.local
        port:
          number: 9080

